name: Create Pull Request
description: |
  This action creates a new pull request.

  ## Usage

  ```yaml
    steps:
      - name: Create Pull Request
        uses: tmknom/create-pull-request-action@v0
        with:
          head-branch: feat/new-branch
  ```

inputs:
  head-branch:
    required: true
    description: The branch that contains commits for the pull request.
  base-branch:
    required: false
    description: The branch into which you want your code merged.
  title:
    required: false
    description: The title for the pull request.
  body:
    required: false
    description: The body for the pull request.

runs:
  using: composite

  steps:
    - name: Create
      env:
        BASE_BRANCH: ${{ inputs.base-branch }}
        HEAD_BRANCH: ${{ inputs.head-branch }}
        TITLE: ${{ inputs.title }}
        BODY: ${{ inputs.body }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "::group::Create"
        set -x
        declare -a flags=(--base "${BASE_BRANCH}" --head "${HEAD_BRANCH}")
        flags+=(--title "${TITLE}")
        flags+=(--body "${BODY}")

        gh pr create "${flags[@]}"
        echo "::endgroup::"
      shell: bash
