name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout default branch
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup
        id: setup
        uses: tmknom/git-push-action@419dadebef56a31a87e80ce1d6388fb13521cf98 # v0.5.1
        with:
          message: 'dummy: ${{ github.job }}/${{ github.run_id }}/${{ github.run_attempt }}'
          branch: pseudo-pr/${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
          start-point: ${{ github.event.repository.default_branch }}
          allow-empty: true

      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        uses: ./
        with:
          head-branch: ${{ steps.setup.outputs.branch }}
          base-branch: ${{ github.event.repository.default_branch }}
          title: ${{ steps.setup.outputs.subject }}
          body: ${{ steps.setup.outputs.body }}

      - name: Verify
        env:
          PR_BRANCH: ${{ steps.setup.outputs.branch }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          actual="$(gh pr view "${PR_BRANCH}" --json 'title,body,baseRefName')"
          test "$(jq -r '.title' <<<"${actual}")" = "dummy: ${GITHUB_JOB}/${GITHUB_RUN_ID}/${GITHUB_RUN_ATTEMPT}"
          test "$(jq -r '.baseRefName' <<<"${actual}")" = "${BASE_BRANCH}"

          body="$(jq -r '.body' <<<"${actual}")"
          grep 'Generated by Test workflow.' <<<"${body}"

      - name: Teardown
        if: ${{ always() }}
        env:
          PR_BRANCH: ${{ steps.setup.outputs.branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr close "${PR_BRANCH}" || true
          git push origin "${PR_BRANCH}" --delete || true
