name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout default branch
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Git Config
        uses: tmknom/git-config-action@970621c4819d5a601bbac4a2bcf6f5f80d92a2e6 # v0.2.0

      - name: Setup
        id: setup
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          pr_branch="pseudo-pr/${GITHUB_JOB}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          title="dummy: ${GITHUB_JOB}/${GITHUB_RUN_ID}/${GITHUB_RUN_ATTEMPT}"
          {
            echo "pr-branch=${pr_branch}"
            echo "title=${title}"
          } >> "${GITHUB_OUTPUT}"

          git switch -c "${pr_branch}" "${DEFAULT_BRANCH}"
          git commit -m "${title}" --allow-empty
          git push origin "${pr_branch}"

      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        uses: ./
        with:
          head-branch: ${{ steps.setup.outputs.pr-branch }}
          base-branch: ${{ github.event.repository.default_branch }}
          title: ${{ steps.setup.outputs.title }}

      - name: Verify
        env:
          PR_BRANCH: ${{ steps.setup.outputs.pr-branch }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          actual="$(gh pr view "${PR_BRANCH}" --json 'title,body,baseRefName')"
          test "$(jq -r '.title' <<<"${actual}")" = "dummy: ${GITHUB_JOB}/${GITHUB_RUN_ID}/${GITHUB_RUN_ATTEMPT}"
          test "$(jq -r '.body' <<<"${actual}")" = ""
          test "$(jq -r '.baseRefName' <<<"${actual}")" = "${BASE_BRANCH}"

      - name: Teardown
        if: ${{ always() }}
        env:
          PR_BRANCH: ${{ steps.setup.outputs.pr-branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr close "${PR_BRANCH}" || true
          git push origin "${PR_BRANCH}" --delete || true
